### ISSUE TITLE
Installation (native build) issue with Ruby 2.2.0

### ISSUE THREAD

**Issue by teeg82** [beoran/chipmunk#21]
When trying to install this gem using the recently released Ruby 2.2.0, I encountered this error:

````
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/paul/.rvm/rubies/ruby-2.2.0/bin/ruby -r ./siteconf20150125-36587-6xnzmu.rb extconf.rb 
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling chipmunk.c
compiling cpArbiter.c
compiling cpArray.c
compiling cpBB.c
compiling cpBBTree.c
compiling cpBody.c
compiling cpCollision.c
compiling cpConstraint.c
compiling cpDampedRotarySpring.c
compiling cpDampedSpring.c
compiling cpGearJoint.c
compiling cpGrooveJoint.c
compiling cpHashSet.c
compiling cpPinJoint.c
compiling cpPivotJoint.c
compiling cpPolyShape.c
compiling cpRatchetJoint.c
compiling cpRotaryLimitJoint.c
compiling cpShape.c
compiling cpSimpleMotor.c
compiling cpSlideJoint.c
compiling cpSpace.c
compiling cpSpaceComponent.c
compiling cpSpaceHash.c
compiling cpSpaceQuery.c
compiling cpSpaceStep.c
compiling cpSpatialIndex.c
compiling cpSweep1D.c
compiling cpVect.c
compiling rb_chipmunk.c
rb_chipmunk.c:40:9: warning: implicit declaration of function 'RHASH' is invalid in C99 [-Wimplicit-function-declaration]
    if (RHASH(cpObjectToIntHash)->ntbl) {
        ^
rb_chipmunk.c:40:35: error: member reference type 'int' is not a pointer
    if (RHASH(cpObjectToIntHash)->ntbl) {
        ~~~~~~~~~~~~~~~~~~~~~~~~  ^
rb_chipmunk.c:41:43: error: member reference type 'int' is not a pointer
      nextInt = RHASH(cpObjectToIntHash)->ntbl->num_entries;
                ~~~~~~~~~~~~~~~~~~~~~~~~  ^
1 warning and 2 errors generated.
make: *** [rb_chipmunk.o] Error 1

make failed, exit code 2
````

I was able to successfully build on the previous Ruby 2.1.5 version. Being uncertain how to solve the issue, I thought I would at least mention it. Please let me know if you need any additional information.

**Comment by nurettin** [comment]
A similar error here

https://github.com/louismullie/treat/issues/91

**Comment by RonJeffries** [comment]
same here

**Comment by shawn42** [comment]
@RonJeffries I've pulled in the pull request for the RHASH_SIZE fix. Unfortunately, chipmunk uses object ids for some of it's internals such as 
```
shape.collision_type = :bouncy_things
```
Chipmunk uses uints to store object ids; object ids are now larger than a uint can hold so some chipmunk internals need to be reworked. I'll try to get a release out shortly, but PRs are welcome.

**Comment by shawn42** [comment]
I have released version 6.1.3.4 that should fix the issue with Ruby 2.2. Thanks @Zeta21 for the PR.
Please test and let me know if you have any problems.
